questone2/cfg/questone2-modules.conf etc/modules-load.d
questone2/cfg/questone2-modprobe.conf etc/modprobe.d
questone2/systemd/platform-modules-questone2.service lib/systemd/system
questone2/cfg/pid_config_questone2.ini usr/local/etc
questone2/scripts/questone2_platform_shutdown.sh usr/local/bin
questone2/scripts/sensors usr/bin
questone2/scripts/platform_sensors.py usr/local/bin
services/platform_api/platform_api_mgnt.sh usr/local/bin
