ds1000/systemd/pddf-platform-init.service etc/systemd/system
ds1000/service/ds1000-fan-control.service lib/systemd/system
ds1000/scripts/pddf_pre_driver_install.sh usr/local/bin
ds1000/scripts/pddf_post_device_create.sh usr/local/bin
ds1000/scripts/ds1000_platform_shutdown.sh usr/local/bin
ds1000/utils/ds1000_fanctld.py usr/local/bin
build-ds1000/sonic_platform-1.0-py3-none-any.whl usr/share/sonic/device/x86_64-cel_ds1000-r0/pddf
services/platform_api/platform_api_mgnt.sh usr/local/bin
