{% from "dockers/dockerfile-macros.j2" import install_debian_packages %}
FROM docker-config-engine-bookworm-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

ARG docker_container_name

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update

COPY \
{% for deb in docker_syncd_mrvl_teralynx_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor -%}
debs/

# Needed for Marvell Teralynx Debug Shell
RUN apt-get install -y net-tools
RUN apt-get install -y libjansson4
RUN apt-get install -y libyaml-dev
RUN apt-get install -y binutils
RUN pip3 install numpy
RUN pip3 install yamlordereddictloader

RUN dpkg -i \
{% for deb in docker_syncd_mrvl_teralynx_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor %}

COPY ["start.sh", "/usr/bin/"]
COPY ["ivm_start.sh", "/usr/bin/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
COPY ["files/supervisor-proc-exit-listener", "/usr/bin"]
COPY ["critical_processes", "/etc/supervisor/"]

## Clean up
RUN apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y
RUN rm -rf /debs

ENTRYPOINT ["/usr/local/bin/supervisord"]
