#!/bin/sh
PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

# Add dhclient and its dependencies
copy_exec /sbin/dhclient /sbin
copy_exec /sbin/dhclient-script /sbin

# Add the necessary network modules
manual_add_modules e1000e
