LIBSAI_MILLENIOB_VERSION = 3.14.0
LIBSAI_MILLENIOB = libsaimilleniob_$(LIBSAI_MILLENIOB_VERSION)_amd64.deb

# Fill the PAI URL here
$(LIBSAI_MILLENIOB)_URL =

ifneq ($($(LIBSAI_MILLENIOB)_URL),)
SONIC_ONLINE_DEBS += $(LIBSAI_MILLENIOB)

DOCKER_GBSYNCD_MILLENIOB_STEM = docker-gbsyncd-milleniob
DOCKER_GBSYNCD_MILLENIOB = $(DOCKER_GBSYNCD_MILLENIOB_STEM).gz
DOCKER_GBSYNCD_MILLENIOB_DBG = $(DOCKER_GBSYNCD_MILLENIOB_STEM)-$(DBG_IMAGE_MARK).gz


$(DOCKER_GBSYNCD_MILLENIOB)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BOOKWORM)

$(DOCKER_GBSYNCD_MILLENIOB)_DBG_DEPENDS += $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_DEPENDS)

$(DOCKER_GBSYNCD_MILLENIOB)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_IMAGE_PACKAGES)

SONIC_DOCKER_IMAGES += $(DOCKER_GBSYNCD_MILLENIOB)
SONIC_BOOKWORM_DOCKERS += $(DOCKER_GBSYNCD_MILLENIOB)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_GBSYNCD_MILLENIOB)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_GBSYNCD_MILLENIOB_DBG)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_GBSYNCD_MILLENIOB_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_GBSYNCD_MILLENIOB_DBG)

$(DOCKER_GBSYNCD_MILLENIOB)_CONTAINER_NAME = gbsyncd
$(DOCKER_GBSYNCD_MILLENIOB)_RUN_OPT += --privileged -t
$(DOCKER_GBSYNCD_MILLENIOB)_RUN_OPT += -v /host/machine.conf:/etc/machine.conf
$(DOCKER_GBSYNCD_MILLENIOB)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_GBSYNCD_MILLENIOB)_RUN_OPT += -v /host/warmboot:/var/warmboot

$(DOCKER_GBSYNCD_MILLENIOB)_VERSION = 1.0.0
$(DOCKER_GBSYNCD_MILLENIOB)_PACKAGE_NAME = gbsyncd-milleniob
$(DOCKER_GBSYNCD_MILLENIOB)_PATH = $(PLATFORM_PATH)/../components/docker-gbsyncd-milleniob
$(DOCKER_GBSYNCD_MILLENIOB)_DEPENDS += $(SYNCD) $(LIBSAI_MILLENIOB)
endif
