# docker dpu image for load
DOCKER_DPU_STEM = docker-dpu

DOCKER_DPU = $(DOCKER_DPU_STEM).gz

$(DOCKER_DPU)_SQUASH = n
$(DOCKER_DPU)_PATH = $(PLATFORM_PATH)/$(DOCKER_DPU_STEM)

$(DOCKER_DPU)_LOAD_DOCKERS = $(DOCKER_DPU_BASE)

SONIC_DOCKER_IMAGES += $(DOCKER_DPU)

$(DOCKER_DPU)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BULLSEYE)

$(DOCKER_DPU)_PACKAGE_NAME = dpu
$(DOCKER_DPU)_CONTAINER_NAME = dpu
$(DOCKER_DPU)_VERSION = 1.0.0

SONIC_BULLSEYE_DOCKERS += $(DOCKER_DPU)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_DPU)
