# Pensando Elba kernel modules

IONIC_MODULE_VERSION = 22.11.1-001

IONIC_MODULE = ionic-modules_$(IONIC_MODULE_VERSION)_arm64.deb
$(IONIC_MODULE)_SRC_PATH = $(PLATFORM_PATH)/dsc-drivers
$(IONIC_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(IONIC_MODULE)_MACHINE = pensando
SONIC_DPKG_DEBS += $(IONIC_MODULE)
