# sonic centec one image installer

SONIC_ONE_IMAGE = sonic-pensando.tar
$(SONIC_ONE_IMAGE)_MACHINE = pensando
$(SONIC_ONE_IMAGE)_IMAGE_TYPE = dsc

$(SONIC_ONE_IMAGE)_INSTALLS += $(SYSTEMD_SONIC_GENERATOR)
$(SONIC_ONE_IMAGE)_INSTALLS += $(DPU_MODULE)
$(SONIC_ONE_IMAGE)_INSTALLS += $(IONIC_MODULE)
$(SONIC_ONE_IMAGE)_INSTALLS += $(PENSANDO_DPU_PLATFORM_MODULE)


DISABLED_DOCKERS = $(DOCKER_SFLOW) $(DOCKER_MGMT_FRAMEWORK) $(DOCKER_NAT) $(DOCKER_TEAMD) $(DOCKER_ROUTER_ADVERTISER) $(DOCKER_MUX) $(DOCKER_SNMP)
DISABLED_PACKAGES_LOCAL = $(DOCKER_DHCP_RELAY) $(DOCKER_MACSEC)
DISABLED_FEATURE_FLAGS = INCLUDE_SFLOW INCLUDE_MGMT_FRAMEWORK INCLUDE_NAT INCLUDE_MACSEC INCLUDE_TEAMD INCLUDE_ROUTER_ADVERTISER INCLUDE_MUX
$(info Disabling the following docker images: $(DISABLED_DOCKERS))
$(info Disabling the following packages:  $(DISABLED_PACKAGES_LOCAL))
$(info Disabling the following feauture flags:  $(DISABLED_FEATURE_FLAGS))

SONIC_PACKAGES_LOCAL := $(filter-out $(DISABLED_PACKAGES_LOCAL), $(SONIC_PACKAGES_LOCAL))
$(foreach feature, $(DISABLED_FEATURE_FLAGS), $(eval override $(feature)=n ))

ifeq ($(INSTALL_DEBUG_TOOLS),y)
$(SONIC_ONE_IMAGE)_DOCKERS += $(SONIC_INSTALL_DOCKER_DBG_IMAGES)
$(SONIC_ONE_IMAGE)_DOCKERS += $(filter-out $(patsubst %-$(DBG_IMAGE_MARK).gz,%.gz, $(SONIC_INSTALL_DOCKER_DBG_IMAGES)), $(filter-out $(DISABLED_DOCKERS), $(SONIC_INSTALL_DOCKER_IMAGES)))
else
$(SONIC_ONE_IMAGE)_DOCKERS = $(filter-out $(DISABLED_DOCKERS), $(SONIC_INSTALL_DOCKER_IMAGES))
endif
SONIC_INSTALLERS += $(SONIC_ONE_IMAGE)
