{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files, rsync_from_builder_stage %}
ARG BASE=docker-config-engine-bookworm-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

FROM $BASE AS base

ARG docker_container_name
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update      && \
    apt-get install -f -y  \
        libdbus-1-3        \
        libdaemon0         \
        libjansson4        \
        libpython3.11      \
        libjemalloc2        \
        ebtables

{% if docker_stp_debs.strip() -%}
# Copy locally-built Debian package dependencies
{{ copy_files("debs/", docker_stp_debs.split(' '), "/debs/") }}

# Install locally-built Debian packages and implicitly install their dependencies
{{ install_debian_packages(docker_stp_debs.split(' ')) }}
{%- endif %}

COPY ["start.sh", "/usr/bin/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
COPY ["critical_processes", "/etc/supervisor"]
RUN chmod +x /usr/bin/start.sh

FROM $BASE

{{ rsync_from_builder_stage() }}

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

ENTRYPOINT ["/usr/local/bin/supervisord"]
