#
# Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES.
# Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Bluefied Software Distribution Version
BFSOC_VERSION = 4.13.0
BFSOC_REVISION = 13798
BFB_IMG_TYPE = prod
BFSOC_BUILD_DATE =

BSD_INTERNAL_BASE_URL = 
BSD_BASE_URL = 
BSD_BASE_SOURCE_URL = 
BFSOC_FROM_INTERNAL = n

ifneq ($(BSD_INTERNAL_BASE_URL), )
BFSOC_FROM_INTERNAL = y
BSD_BASE_URL = $(BSD_INTERNAL_BASE_URL)
ifneq ($(BFSOC_BUILD_DATE), )
BSD_BASE_URL = $(BSD_INTERNAL_BASE_URL)/$(BFSOC_BUILD_DATE)
endif

BSD_BASE_SOURCE_URL = $(BSD_BASE_URL)/install/distro/SRPMS/
QP_BOOTIMAGES_BASE_URL = $(BSD_BASE_URL)/install/distro/DEBS/
DEV_BOOTIMAGES_BASE_URL = $(BSD_BASE_URL)/install/distro/dev-release/DEBS/
PROD_BOOTIMAGES_BASE_URL = $(BSD_BASE_URL)/install/distro/ga-release/DEBS/
endif

export BFSOC_VERSION BFSOC_REVISION BSD_BASE_URL BSD_BASE_SOURCE_URL BFB_IMG_TYPE BFSOC_FROM_INTERNAL PLATFORM_PATH

define make_url_bfsoc
	$(1)_URL="https://github.com/Mellanox/sonic-bluefield-packages/releases/download/dpu-bfsoc-$(BFSOC_VERSION)-$(BFSOC_REVISION)-$(BLDENV)/$(1)"

endef

BF_PLATFORM_DRIVERS =
BFSOC_DKMS_DEBS =
BFSOC_MAKE_DEBS =
BFSOC_MAKE_DEBS_DERIVED =
BFSOC_ONLINE_DEBS =

MLXBF3_PINCTRL_DRIVER = pinctrl-mlxbf3
MLXBF3_PINCTRL_DRIVER_DKMS = $(MLXBF3_PINCTRL_DRIVER)-dkms_1.0-0_all.deb
$(MLXBF3_PINCTRL_DRIVER_DKMS)_SRC_PATH = $(PLATFORM_PATH)/pinctrl-mlxbf3
$(MLXBF3_PINCTRL_DRIVER_DKMS)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
BFSOC_DKMS_DEBS += $(MLXBF3_PINCTRL_DRIVER_DKMS)
BF_PLATFORM_DRIVERS += $(MLXBF3_PINCTRL_DRIVER)
export MLXBF3_PINCTRL_DRIVER MLXBF3_PINCTRL_DRIVER_DKMS

TMFIFO_DRIVER = mlxbf-tmfifo
TMFIFO_DRIVER_DKMS = $(TMFIFO_DRIVER)-dkms_1.0-0_all.deb
$(TMFIFO_DRIVER_DKMS)_SRC_PATH = $(PLATFORM_PATH)/tmfifo
$(TMFIFO_DRIVER_DKMS)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
BFSOC_DKMS_DEBS += $(TMFIFO_DRIVER_DKMS)
BF_PLATFORM_DRIVERS += $(TMFIFO_DRIVER)
export TMFIFO_DRIVER TMFIFO_DRIVER_DKMS

MLXBF_GIGE_DRIVER = mlxbf-gige
MLXBF_GIGE_DRIVER_DKMS = $(MLXBF_GIGE_DRIVER)-dkms_1.0-0_all.deb
$(MLXBF_GIGE_DRIVER_DKMS)_SRC_PATH = $(PLATFORM_PATH)/mlxbf-gige
$(MLXBF_GIGE_DRIVER_DKMS)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
BFSOC_DKMS_DEBS += $(MLXBF_GIGE_DRIVER_DKMS)
BF_PLATFORM_DRIVERS += $(MLXBF_GIGE_DRIVER)
export MLXBF_GIGE_DRIVER MLXBF_GIGE_DRIVER_DKMS

MLXBF3_GPIO_DRIVER = gpio-mlxbf3
MLXBF3_GPIO_DRIVER_DKMS = $(MLXBF3_GPIO_DRIVER)-dkms_1.0-0_all.deb
$(MLXBF3_GPIO_DRIVER_DKMS)_SRC_PATH = $(PLATFORM_PATH)/gpio-mlxbf3
$(MLXBF3_GPIO_DRIVER_DKMS)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
BFSOC_DKMS_DEBS += $(MLXBF3_GPIO_DRIVER_DKMS)
BF_PLATFORM_DRIVERS += $(MLXBF3_GPIO_DRIVER)
export MLXBF3_GPIO_DRIVER MLXBF3_GPIO_DRIVER_DKMS

MLX_BOOTCTL_DRIVER = mlx-bootctl
MLX_BOOTCTL_DRIVER_DKMS = $(MLX_BOOTCTL_DRIVER)-dkms_1.3-0_all.deb
$(MLX_BOOTCTL_DRIVER_DKMS)_SRC_PATH = $(PLATFORM_PATH)/mlx-bootctl
$(MLX_BOOTCTL_DRIVER_DKMS)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
BFSOC_DKMS_DEBS += $(MLX_BOOTCTL_DRIVER_DKMS)
export MLX_BOOTCTL_DRIVER MLX_BOOTCTL_DRIVER_DKMS

SDHCI_OF_DWCMSHC_DRIVER = sdhci-of-dwcmshc
SDHCI_OF_DWCMSHC_DRIVER_DKMS = $(SDHCI_OF_DWCMSHC_DRIVER)-dkms_1.0-0_all.deb
$(SDHCI_OF_DWCMSHC_DRIVER_DKMS)_SRC_PATH = $(PLATFORM_PATH)/sdhci-of-dwcmshc
$(SDHCI_OF_DWCMSHC_DRIVER_DKMS)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
BFSOC_DKMS_DEBS += $(SDHCI_OF_DWCMSHC_DRIVER_DKMS)
BF_PLATFORM_DRIVERS += $(SDHCI_OF_DWCMSHC_DRIVER)
export SDHCI_OF_DWCMSHC_DRIVER SDHCI_OF_DWCMSHC_DRIVER_DKMS

MLXBF_PKA_DRIVER = mlxbf-pka
MLXBF_PKA_DRIVER_DKMS = $(MLXBF_PKA_DRIVER)-dkms_2.0-1_all.deb
$(MLXBF_PKA_DRIVER_DKMS)_SRC_PATH = $(PLATFORM_PATH)/mlxbf-pka
$(MLXBF_PKA_DRIVER_DKMS)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
BFSOC_DKMS_DEBS += $(MLXBF_PKA_DRIVER_DKMS)
BF_PLATFORM_DRIVERS += $(MLXBF_PKA_DRIVER)
export MLXBF_PKA_DRIVER MLXBF_PKA_DRIVER_DKMS

PWR_MLXBF_DRIVER = pwr-mlxbf
PWR_MLXBF_DRIVER_DKMS = $(PWR_MLXBF_DRIVER)-dkms_1.0-0_all.deb
$(PWR_MLXBF_DRIVER_DKMS)_SRC_PATH = $(PLATFORM_PATH)/pwr-mlxbf
$(PWR_MLXBF_DRIVER_DKMS)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
BFSOC_DKMS_DEBS += $(PWR_MLXBF_DRIVER_DKMS)
BF_PLATFORM_DRIVERS += $(PWR_MLXBF_DRIVER)
export PWR_MLXBF_DRIVER PWR_MLXBF_DRIVER_DKMS

MLXBF_PTM_DRIVER = mlxbf-ptm
MLXBF_PTM_DRIVER_DKMS = $(MLXBF_PTM_DRIVER)-dkms_1.0-0_all.deb
$(MLXBF_PTM_DRIVER_DKMS)_SRC_PATH = $(PLATFORM_PATH)/mlxbf-ptm
$(MLXBF_PTM_DRIVER_DKMS)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
BFSOC_DKMS_DEBS += $(MLXBF_PTM_DRIVER_DKMS)
BF_PLATFORM_DRIVERS += $(MLXBF_PTM_DRIVER)
export MLXBF_PTM_DRIVER MLXBF_PTM_DRIVER_DKMS

MLXBF_BOOTCTL_DEB_VERSION = 2.1
MLXBF_BOOTCTL_DEB = mlxbf-bootctl_${MLXBF_BOOTCTL_DEB_VERSION}_${CONFIGURED_ARCH}.deb
$(MLXBF_BOOTCTL_DEB)_SRC_PATH = $(PLATFORM_PATH)/mlxbf-bootctl

BFSOC_MAKE_DEBS += $(MLXBF_BOOTCTL_DEB)
export MLXBF_BOOTCTL_DEB_VERSION MLXBF_BOOTCTL_DEB

ifeq ($(BFB_IMG_TYPE), qp)
BOOTIMAGES_BASE_URL = $(QP_BOOTIMAGES_BASE_URL)
BOOTIMAGES = mlxbf-bootimages_$(BFSOC_VERSION)-$(BFSOC_REVISION)_arm64.deb
else ifeq ($(BFB_IMG_TYPE), prod)
BOOTIMAGES_BASE_URL = $(PROD_BOOTIMAGES_BASE_URL)
BOOTIMAGES = mlxbf-bootimages-signed_$(BFSOC_VERSION)-$(BFSOC_REVISION)_arm64.deb
else
BOOTIMAGES_BASE_URL = $(DEV_BOOTIMAGES_BASE_URL)
BOOTIMAGES = mlxbf-bootimages-devsigned_$(BFSOC_VERSION)-$(BFSOC_REVISION)_arm64.deb
endif

$(BOOTIMAGES)_URL = $(BOOTIMAGES_BASE_URL)/$(BOOTIMAGES)

BFSOC_ONLINE_DEBS += $(BOOTIMAGES)
export BOOTIMAGES BOOTIMAGES_BASE_URL

MLNX_BLUEFIELD_BUILD_SCRIPTS =  bfscripts_$(BFSOC_VERSION)-$(BFSOC_REVISION)_all.deb
$(MLNX_BLUEFIELD_BUILD_SCRIPTS)_SRC_PATH = $(PLATFORM_PATH)/bfscripts
$(MLNX_BLUEFIELD_BUILD_SCRIPTS)_DEPENDS += $(MLXBF_BOOTCTL_DEB) $(BOOTIMAGES)
$(MLNX_BLUEFIELD_BUILD_SCRIPTS)_RDEPENDS += $(MLXBF_BOOTCTL_DEB) $(BOOTIMAGES)

BFSOC_MAKE_DEBS += $(MLNX_BLUEFIELD_BUILD_SCRIPTS)
export MLNX_BLUEFIELD_BUILD_SCRIPTS

BF_PLATFORM_MODULE_VERSION = 2.0
BF_PLATFORM_MODULE = bluefield-platform-modules_$(BF_PLATFORM_MODULE_VERSION)_arm64.deb
$(BF_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/bluefield-platform-modules
$(BF_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(BFSOC_DKMS_DEBS)
export BF_PLATFORM_MODULE_VERSION BF_PLATFORM_MODULE BF_PLATFORM_DRIVERS

ifeq ($(BFSOC_FROM_INTERNAL), y)
SONIC_MAKE_DEBS += $(BFSOC_MAKE_DEBS) $(BFSOC_DKMS_DEBS)
SONIC_ONLINE_DEBS += $(BFSOC_ONLINE_DEBS)
else
$(eval $(foreach file, $(BFSOC_MAKE_DEBS) $(BFSOC_DKMS_DEBS) $(BFSOC_MAKE_DEBS_DERIVED) $(BFSOC_ONLINE_DEBS), $(call make_url_bfsoc,$(file))))
SONIC_ONLINE_DEBS += $(BFSOC_MAKE_DEBS) $(BFSOC_DKMS_DEBS) $(BFSOC_MAKE_DEBS_DERIVED) $(BFSOC_ONLINE_DEBS)
endif

# Always build the platform modules, don't save the deb file to artifactory
SONIC_MAKE_DEBS += $(BF_PLATFORM_MODULE)
