#  Copyright (C) Marvell Inc

# over ride default behaviour

echo "Preparing for installation ... "

# global defines
VAR_LOG=4096
UBOOT_FW_DEFAULT=1

is_uefi_based=1
PLATFORM_7215_C1=0
disk_interface="mmc"

if [ "$install_env" = "onie" ]; then
    MACH_FILE="/etc/machine.conf"
else
    MACH_FILE="/host/machine.conf"
fi

PLATFORM=`sed -n 's/^onie_platform=\(.*\)/\1/p' $MACH_FILE`
echo "Intalling SONiC from $install_env on Platform $PLATFORM"

case $PLATFORM in
    arm64-nokia_ixs7215_c1xa-r0) PLATFORM_7215_C1=1;
		mmc_bus="mmc0:0001";
esac


# Skip VID Header in UBIFS
LINUX_MISC_CMD='apparmor=1 security=apparmor usbcore.autosuspend=-1'

# Get block device
# default_platform.conf will by default install SONIC on same block device as ONIE
# This funtion looks to override SONIC install target disk, with optional eMMC or SCSI disk.
get_install_device()
{
    if [ ! -z "$mmc_bus" ]; then
        for i in 0 1 2 ; do
            if $(ls -l /sys/block/mmcblk$i/device 2>/dev/null | grep -q "$mmc_bus") ; then
                echo "/dev/mmcblk$i"
                blk_dev=/dev/mmcblk$i
                disk_interface="mmc"
                echo "Selected mmc $blk_dev"
                return
            fi
        done
    fi

    echo "Waring: Storage not found. Will try installing on the same disk as ONIE."
}

get_install_device
