# postinst script for Z9864f

# Enable Dell-Z9864f-platform-service
depmod -a
pip3 install /usr/share/sonic/device/x86_64-dell_z9864f-r0/sonic_platform-1.0-py3-none-any.whl --force-reinstall -q --root-user-action=ignore
systemctl enable platform-modules-z9864f.service
systemctl start platform-modules-z9864f.service
systemctl enable system-health.service
systemctl start --no-block system-health.service


#DEBHELPER#
