# Marvell Teralynx platform package
export MRVL_TERALYNX_VER = 1.0
export MRVL_TERALYNX = mrvlteralynx_$(MRVL_TERALYNX_VER)_$(PLATFORM_ARCH)
export MRVL_TERALYNX_DEB = $(MRVL_TERALYNX).deb

$(MRVL_TERALYNX_DEB)_SRC_PATH = $(PLATFORM_PATH)/mrvl-teralynx
$(MRVL_TERALYNX_DEB)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)

SONIC_DPKG_DEBS += $(MRVL_TERALYNX_DEB)
