export OR_TOOLS_VERSION = 9.11
export OR_TOOLS_VERSION_FULL = $(OR_TOOLS_VERSION)-1

LIBOR_TOOLS = libortools_$(OR_TOOLS_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(LIBOR_TOOLS)_SRC_PATH = $(PLATFORM_PATH)/or-tools
SONIC_MAKE_DEBS += $(LIBOR_TOOLS)
