# MRVL_TERALYNX SAI

MRVL_TERALYNX_SAI_ONLINE = https://github.com/Marvell-switching/sonic-marvell-teralynx-binaries/raw/main/debian/master

MRVL_TERALYNX_LIBSAI = isai.deb
MRVL_TERALYNX_HSAI   = saihdr.deb
MRVL_TERALYNX_DRV    = ipd.deb
MRVL_TERALYNX_SHELL  = ishell.deb

$(MRVL_TERALYNX_LIBSAI)_URL = $(MRVL_TERALYNX_SAI_ONLINE)/$(MRVL_TERALYNX_LIBSAI)
$(MRVL_TERALYNX_HSAI)_URL   =  $(MRVL_TERALYNX_SAI_ONLINE)/$(MRVL_TERALYNX_HSAI)
$(MRVL_TERALYNX_DRV)_URL    =  $(MRVL_TERALYNX_SAI_ONLINE)/$(MRVL_TERALYNX_DRV)
$(MRVL_TERALYNX_SHELL)_URL  =  $(MRVL_TERALYNX_SAI_ONLINE)/$(MRVL_TERALYNX_SHELL)

$(eval $(call add_conflict_package,$(MRVL_TERALYNX_HSAI),$(LIBSAIVS_DEV)))

SONIC_ONLINE_DEBS  += $(MRVL_TERALYNX_LIBSAI) $(MRVL_TERALYNX_HSAI) $(MRVL_TERALYNX_DRV) $(MRVL_TERALYNX_SHELL)
