# docker image for brcm-legacy syncd

DOCKER_SYNCD_LEGACY_BASE = docker-syncd-brcm-legacy.gz
DOCKER_SYNCD_LEGACY_BASE_DBG = docker-syncd-brcm-legacy-$(DBG_IMAGE_MARK).gz
DOCKER_SYNCD_LEGACY_PLATFORM_CODE = brcm-legacy

$(DOCKER_SYNCD_LEGACY_BASE)_PATH = $(PLATFORM_PATH)/docker-syncd-$(DOCKER_SYNCD_LEGACY_PLATFORM_CODE)

$(DOCKER_SYNCD_LEGACY_BASE)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BOOKWORM)
$(DOCKER_SYNCD_LEGACY_BASE)_DBG_DEPENDS += $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_DEPENDS)
$(DOCKER_SYNCD_LEGACY_BASE)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_IMAGE_PACKAGES)

SONIC_DOCKER_IMAGES += $(DOCKER_SYNCD_LEGACY_BASE)
ifneq ($(ENABLE_SYNCD_RPC),y)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_SYNCD_LEGACY_BASE)
endif

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_SYNCD_LEGACY_BASE_DBG)
ifneq ($(ENABLE_SYNCD_RPC),y)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_SYNCD_LEGACY_BASE_DBG)
endif


$(DOCKER_SYNCD_LEGACY_BASE)_DEPENDS += $(SYNCD)
$(DOCKER_SYNCD_LEGACY_BASE)_DEPENDS += $(BRCM_LEGACY_SAI)
$(DOCKER_SYNCD_LEGACY_BASE)_DEPENDS += $(SSWSYNCD)
$(DOCKER_SYNCD_LEGACY_BASE)_FILES += $(RDB-CLI)

ifeq ($(INSTALL_DEBUG_TOOLS), y)
$(DOCKER_SYNCD_LEGACY_BASE)_DBG_DEPENDS += $(SYNCD_DBG) \
                                $(LIBSWSSCOMMON_DBG) \
                                $(LIBSAIMETADATA_DBG) \
                                $(LIBSAIREDIS_DBG)
endif

$(DOCKER_SYNCD_LEGACY_BASE)_VERSION = 1.0.0
$(DOCKER_SYNCD_LEGACY_BASE)_PACKAGE_NAME = syncd-legacy
$(DOCKER_SYNCD_LEGACY_BASE)_MACHINE = broadcom-legacy
$(DOCKER_SYNCD_LEGACY_BASE)_AFTER = $(DOCKER_SYNCD_DNX_BASE)
$(DOCKER_SYNCD_LEGACY_BASE)_CONTAINER_NAME = syncd

$(DOCKER_SYNCD_LEGACY_BASE)_RUN_OPT += --privileged -t
$(DOCKER_SYNCD_LEGACY_BASE)_RUN_OPT += -v /host/machine.conf:/etc/machine.conf
$(DOCKER_SYNCD_LEGACY_BASE)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_SYNCD_LEGACY_BASE)_RUN_OPT += -v /host/warmboot:/var/warmboot

$(DOCKER_SYNCD_LEGACY_BASE)_BASE_IMAGE_FILES += bcmcmd:/usr/bin/bcmcmd
$(DOCKER_SYNCD_LEGACY_BASE)_BASE_IMAGE_FILES += bcmsh:/usr/bin/bcmsh
$(DOCKER_SYNCD_LEGACY_BASE)_BASE_IMAGE_FILES += bcm_common:/usr/bin/bcm_common

SONIC_BOOKWORM_DOCKERS += $(DOCKER_SYNCD_LEGACY_BASE)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_SYNCD_LEGACY_BASE_DBG)
