# Nexthop Platform modules

# Common
NEXTHOP_COMMON_PLATFORM_MODULE = sonic-platform-nexthop-common_1.0_amd64.deb
$(NEXTHOP_COMMON_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-nexthop
$(NEXTHOP_COMMON_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(PDDF_PLATFORM_MODULE_SYM)
$(NEXTHOP_COMMON_PLATFORM_MODULE)_PLATFORM = nexthop-common
SONIC_DPKG_DEBS += $(NEXTHOP_COMMON_PLATFORM_MODULE)
SONIC_STRETCH_DEBS += $(NEXTHOP_COMMON_PLATFORM_MODULE)

# CPU Card
NEXTHOP_KOMODO_PLATFORM_MODULE = sonic-platform-nexthop-komodo_1.0_amd64.deb
$(NEXTHOP_KOMODO_PLATFORM_MODULE)_PLATFORM = nexthop-komodo
$(eval $(call add_extra_package,$(NEXTHOP_COMMON_PLATFORM_MODULE),$(NEXTHOP_KOMODO_PLATFORM_MODULE)))

# NH-4010
NEXTHOP_4010_PLATFORM_MODULE = sonic-platform-nexthop-4010_1.0_amd64.deb
$(NEXTHOP_4010_PLATFORM_MODULE)_PLATFORM = nexthop-4010
$(eval $(call add_extra_package,$(NEXTHOP_COMMON_PLATFORM_MODULE),$(NEXTHOP_4010_PLATFORM_MODULE)))

NEXTHOP_4010_R0_PLATFORM_MODULE = sonic-platform-nexthop-4010-r0_1.0_amd64.deb
$(NEXTHOP_4010_R0_PLATFORM_MODULE)_PLATFORM = x86_64-nexthop_4010-r0
$(eval $(call add_extra_package,$(NEXTHOP_COMMON_PLATFORM_MODULE),$(NEXTHOP_4010_R0_PLATFORM_MODULE)))

NEXTHOP_4010_R1_PLATFORM_MODULE = sonic-platform-nexthop-4010-r1_1.0_amd64.deb
$(NEXTHOP_4010_R1_PLATFORM_MODULE)_PLATFORM = x86_64-nexthop_4010-r1
$(eval $(call add_extra_package,$(NEXTHOP_COMMON_PLATFORM_MODULE),$(NEXTHOP_4010_R1_PLATFORM_MODULE)))

# NH-4020
NEXTHOP_4020_R0_PLATFORM_MODULE = sonic-platform-nexthop-4020-r0_1.0_amd64.deb
$(NEXTHOP_4020_R0_PLATFORM_MODULE)_PLATFORM = x86_64-nexthop_4020-r0
$(eval $(call add_extra_package,$(NEXTHOP_COMMON_PLATFORM_MODULE),$(NEXTHOP_4020_R0_PLATFORM_MODULE)))

# NH-4220
NEXTHOP_4220_PLATFORM_MODULE = sonic-platform-nexthop-4220_1.0_amd64.deb
$(NEXTHOP_4220_PLATFORM_MODULE)_PLATFORM = nexthop-4220
$(eval $(call add_extra_package,$(NEXTHOP_COMMON_PLATFORM_MODULE),$(NEXTHOP_4220_PLATFORM_MODULE)))

NEXTHOP_4220_R0_PLATFORM_MODULE = sonic-platform-nexthop-4220-r0_1.0_amd64.deb
$(NEXTHOP_4220_R0_PLATFORM_MODULE)_PLATFORM = x86_64-nexthop_4220-r0
$(eval $(call add_extra_package,$(NEXTHOP_COMMON_PLATFORM_MODULE),$(NEXTHOP_4220_R0_PLATFORM_MODULE)))

# NH-5010
NEXTHOP_5010_PLATFORM_MODULE = sonic-platform-nexthop-5010_1.0_amd64.deb
$(NEXTHOP_5010_PLATFORM_MODULE)_PLATFORM = nexthop-5010
$(eval $(call add_extra_package,$(NEXTHOP_COMMON_PLATFORM_MODULE),$(NEXTHOP_5010_PLATFORM_MODULE)))

NEXTHOP_5010_R0_PLATFORM_MODULE = sonic-platform-nexthop-5010-r0_1.0_amd64.deb
$(NEXTHOP_5010_R0_PLATFORM_MODULE)_PLATFORM = x86_64-nexthop_5010-r0
$(eval $(call add_extra_package,$(NEXTHOP_COMMON_PLATFORM_MODULE),$(NEXTHOP_5010_R0_PLATFORM_MODULE)))
