# Nexthop Platform modules

NEXTHOP_4010_PLATFORM_MODULE_VERSION = 1.0

export NEXTHOP_4010_PLATFORM_MODULE_VERSION

NEXTHOP_4010_PLATFORM_MODULE = sonic-platform-nexthop-4010_$(NEXTHOP_4010_PLATFORM_MODULE_VERSION)_amd64.deb
$(NEXTHOP_4010_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-nexthop
$(NEXTHOP_4010_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(PDDF_PLATFORM_MODULE_SYM)
$(NEXTHOP_4010_PLATFORM_MODULE)_PLATFORM = x86_64-nexthop_4010-r0
SONIC_DPKG_DEBS += $(NEXTHOP_4010_PLATFORM_MODULE)
SONIC_STRETCH_DEBS += $(NEXTHOP_4010_PLATFORM_MODULE)
