# Broadcom LEGACY-TH SAI definitions
LIBSAIBCM_LEGACY_TH_VERSION = 13.2.1.100
LIBSAIBCM_LEGACY_TH_BRANCH_NAME = SAI_13.2.1_compat_OCP1.17.1

LIBSAIBCM_LEGACY_TH_URL_PREFIX = "https://packages.trafficmanager.net/public/sai/sai-broadcom/$(LIBSAIBCM_LEGACY_TH_BRANCH_NAME)/$(LIBSAIBCM_LEGACY_TH_VERSION)/xgs"

# SAI module for LEGACY-TH Asic family
BRCM_LEGACY_TH_SAI = libsaibcm_$(LIBSAIBCM_LEGACY_TH_VERSION)_amd64.deb
$(BRCM_LEGACY_TH_SAI)_URL = "$(LIBSAIBCM_LEGACY_TH_URL_PREFIX)/$(BRCM_LEGACY_TH_SAI)"

# Package registration
SONIC_ONLINE_DEBS += $(BRCM_LEGACY_TH_SAI)

# Version handling
$(BRCM_LEGACY_TH_SAI)_SKIP_VERSION=y
