# Aspeed EVB Platform modules
#
ASPEED_EVB_AST2700_PLATFORM_MODULE = sonic-platform-ast-evb-ast2700_1.0_arm64.deb
$(ASPEED_EVB_AST2700_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-ast-evb
$(ASPEED_EVB_AST2700_PLATFORM_MODULE)_PLATFORM = arm64-aspeed_ast2700_evb-r0
SONIC_DPKG_DEBS += $(ASPEED_EVB_AST2700_PLATFORM_MODULE)
