#!/bin/sh
set -e
PREREQ=""
prereqs() {
    echo "$PREREQ"
}
case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac
. /usr/share/initramfs-tools/hook-functions
# Include file binary
copy_exec /usr/bin/file /usr/bin
# Include magic database
copy_exec /usr/lib/file/magic.mgc /etc
exit 0
