# Clounix Platform modules

VERSION = 1.0.1

CLOUNIX_MODULE = clounix-modules_$(VERSION)_amd64.deb
$(CLOUNIX_MODULE)_SRC_PATH = $(PLATFORM_PATH)/clounix-modules
$(CLOUNIX_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(CLOUNIX_SAI)
SONIC_DPKG_DEBS += $(CLOUNIX_MODULE)
