# name          lanes             alias             index       speed
Ethernet0               1         etp1                1          1000
Ethernet1               2         etp2                2          1000
Ethernet2               3         etp3                3          1000
