#!/bin/sh

# This file was originally created automatically as part of default NTP application installation from debian package.
# This is now manually modified for supporting NTP in management VRF.
# When management VRF is enabled, the NTP application should be started using "cgexec -g l3mdev:mgmt". 
# Check has been added to verify the management VRF enabled status and use cgexec when it is enabled.
# This file will be copied on top of the etc/init.d/ntpsec file that gets created during build process.

### BEGIN INIT INFO
# Provides:        ntpsec
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start NTP daemon
# Description:       NTP, the Network Time Protocol, is used to keep computer
#                    clocks accurate by synchronizing them over the Internet or
#                    a local network, or by following an accurate hardware
#                    receiver that interprets GPS, DCF-77, or similar time
#                    signals.
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/usr/sbin/ntpd
PIDFILE=/run/ntpd.pid

test -x $DAEMON || exit 5

if [ -r /etc/default/ntpsec ]; then
	. /etc/default/ntpsec
fi

if [ "$IGNORE_DHCP" != "yes" ] && [ -e /run/ntpsec/ntp.conf.dhcp ]; then
	NTPD_OPTS="$NTPD_OPTS -c /run/ntpsec/ntp.conf.dhcp"
else
	# List the default -c first, so if the admin has specified -c in
	# NTPD_OPTS, it is honored.
	NTPD_OPTS="-c /etc/ntpsec/ntp.conf $NTPD_OPTS"
fi

NTPD_OPTS="$NTPD_OPTS -u ntpsec:ntpsec"

LOCKFILE=/run/lock/ntpsec-ntpdate

case $1 in
	start)
		log_daemon_msg "Starting NTP server" "ntpd"
		(
			flock -w 180 9

			# when mgmt vrf is configured, ntp starts in mgmt vrf by default unless user configures otherwise
			vrfEnabled=$(/usr/local/bin/sonic-cfggen -d -v 'MGMT_VRF_CONFIG["vrf_global"]["mgmtVrfEnabled"]' 2> /dev/null)
			vrfConfigured=$(/usr/local/bin/sonic-cfggen -d -v 'NTP["global"]["vrf"]' 2> /dev/null)
			if [ "$vrfEnabled" = "true" ]
			then
				if [ "$vrfConfigured" = "default" ]
				then
					log_daemon_msg "Starting NTP server in default-vrf for default set as NTP vrf" "ntpd"
					start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- -p $PIDFILE $NTPD_OPTS
				else
					log_daemon_msg "Starting NTP server in mgmt-vrf" "ntpd"
					cgexec -g l3mdev:mgmt start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- -p $PIDFILE $NTPD_OPTS
				fi
			else
				log_daemon_msg "Starting NTP server in default-vrf" "ntpd"
				start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- -p $PIDFILE $NTPD_OPTS
			fi
		) 9>$LOCKFILE
		log_end_msg $?
		;;
	stop)
		log_daemon_msg "Stopping NTP server" "ntpd"
		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --retry=TERM/30/KILL/5 --exec $DAEMON
		log_end_msg $?
		rm -f $PIDFILE
		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON "NTP server"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
