MPATH       := $($(MICAS_M2_W6010_48GT4X_PLATFORM_MODULE)_SRC_PATH)
DEP_FILES   := $(SONIC_COMMON_FILES_LIST) platform/centec-arm64/platform-modules-micas.mk platform/centec-arm64/platform-modules-micas.dep
DEP_FILES   += $(SONIC_COMMON_BASE_FILES_LIST)
DEP_FILES += $(addprefix $(MPATH)/,$(shell cd $(MPATH) && git ls-files))

$(MICAS_M2_W6010_48GT4X_PLATFORM_MODULE)_CACHE_MODE  := GIT_CONTENT_SHA 
$(MICAS_M2_W6010_48GT4X_PLATFORM_MODULE)_DEP_FLAGS   := $(SONIC_COMMON_FLAGS_LIST)
$(MICAS_M2_W6010_48GT4X_PLATFORM_MODULE)_DEP_FILES   := $(DEP_FILES)

