# DASH SAI repo: https://github.com/sonic-net/DASH

DASH_SAI_VERSION = 1.0.0
DASH_SAI_COMMIT = 57e599c9d8e1f538ea01fad28781d8a0c2706ba5

export DASH_SAI_VERSION
export DASH_SAI_COMMIT

DASH_SAI = libsai_$(DASH_SAI_VERSION)_$(CONFIGURED_ARCH).deb
$(DASH_SAI)_SRC_PATH = $(SRC_PATH)/dash-sai
$(DASH_SAI)_DEPENDS = $(P4LANG_PI) $(P4LANG_BMV2) $(P4LANG_P4C)
$(DASH_SAI)_RDEPENDS = $(P4LANG_PI) $(P4LANG_BMV2) $(P4LANG_P4C)
SONIC_MAKE_DEBS += $(DASH_SAI)

DASH_SAI_DEV = libsai-dev_$(DASH_SAI_VERSION)_$(CONFIGURED_ARCH).deb
$(DASH_SAI_DEV)_DEPENDS = $(DASH_SAI)
$(eval $(call add_derived_package,$(DASH_SAI),$(DASH_SAI_DEV)))
