# docker image for sonic-redfish (bmcweb + sonic-dbus-bridge)

DOCKER_SONIC_REDFISH_STEM = docker-sonic-redfish
DOCKER_SONIC_REDFISH = $(DOCKER_SONIC_REDFISH_STEM).gz
DOCKER_SONIC_REDFISH_DBG = $(DOCKER_SONIC_REDFISH_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_SONIC_REDFISH)_PATH = $(DOCKERS_PATH)/$(DOCKER_SONIC_REDFISH_STEM)

$(DOCKER_SONIC_REDFISH)_DEPENDS += $(BMCWEB) $(SONIC_DBUS_BRIDGE)
$(DOCKER_SONIC_REDFISH)_DBG_DEPENDS = $($(DOCKER_SONIC_REDFISH)_DEPENDS)

$(DOCKER_SONIC_REDFISH)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_TRIXIE)

$(DOCKER_SONIC_REDFISH)_VERSION = 1.0.0
$(DOCKER_SONIC_REDFISH)_PACKAGE_NAME = redfish

SONIC_DOCKER_IMAGES += $(DOCKER_SONIC_REDFISH)
SONIC_TRIXIE_DOCKERS += $(DOCKER_SONIC_REDFISH)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_SONIC_REDFISH_DBG)
SONIC_TRIXIE_DBG_DOCKERS += $(DOCKER_SONIC_REDFISH_DBG)

$(DOCKER_SONIC_REDFISH)_CONTAINER_NAME = redfish
$(DOCKER_SONIC_REDFISH)_RUN_OPT += -t
$(DOCKER_SONIC_REDFISH)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_SONIC_REDFISH)_RUN_OPT += -v /host/machine.conf:/host/machine.conf:ro
$(DOCKER_SONIC_REDFISH)_RUN_OPT += -v /var/lib/bmcweb:/var/lib/bmcweb:rw
$(DOCKER_SONIC_REDFISH)_RUN_OPT += -v /var/run/redis:/var/run/redis:rw
$(DOCKER_SONIC_REDFISH)_RUN_OPT += -v /var/run/dbus:/var/run/dbus:rw
$(DOCKER_SONIC_REDFISH)_RUN_OPT += -p 0.0.0.0:443:18080

