# docker image for restapi watchdog

DOCKER_RESTAPI_WATCHDOG_STEM = docker-restapi-watchdog
DOCKER_RESTAPI_WATCHDOG = $(DOCKER_RESTAPI_WATCHDOG_STEM).gz
DOCKER_RESTAPI_WATCHDOG_DBG = $(DOCKER_RESTAPI_WATCHDOG_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_RESTAPI_WATCHDOG)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BOOKWORM)
$(DOCKER_RESTAPI_WATCHDOG)_PATH = $(DOCKERS_PATH)/$(DOCKER_RESTAPI_WATCHDOG_STEM)

$(DOCKER_RESTAPI_WATCHDOG)_VERSION = 1.0.0
$(DOCKER_RESTAPI_WATCHDOG)_PACKAGE_NAME = restapi_watchdog

SONIC_DOCKER_IMAGES += $(DOCKER_RESTAPI_WATCHDOG)
SONIC_BOOKWORM_DOCKERS += $(DOCKER_RESTAPI_WATCHDOG)
ifeq ($(INCLUDE_RESTAPI), y)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_RESTAPI_WATCHDOG)
endif

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_RESTAPI_WATCHDOG_DBG)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_RESTAPI_WATCHDOG_DBG)
ifeq ($(INCLUDE_RESTAPI), y)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_RESTAPI_WATCHDOG_DBG)
endif

$(DOCKER_RESTAPI_WATCHDOG)_CONTAINER_NAME = restapi_watchdog
$(DOCKER_RESTAPI_WATCHDOG)_RUN_OPT += -t
$(DOCKER_RESTAPI_WATCHDOG)_RUN_OPT += -v /etc/localtime:/etc/localtime:ro
