# docker image for sonic-mgmt
DOCKER_SONIC_MGMT = docker-sonic-mgmt.gz
$(DOCKER_SONIC_MGMT)_PATH = $(DOCKERS_PATH)/docker-sonic-mgmt
$(DOCKER_SONIC_MGMT)_DEPENDS += $(SONIC_DEVICE_DATA) $(PTF) $(LIB_SONIC_DASH_API)
$(DOCKER_SONIC_MGMT)_FILES += $(GITHUB_GET)
SONIC_DOCKER_IMAGES += $(DOCKER_SONIC_MGMT)
SONIC_BULLSEYE_DOCKERS += $(DOCKER_SONIC_MGMT)
