# docker image for auditd

DOCKER_AUDITD_STEM = docker-auditd
DOCKER_AUDITD = $(DOCKER_AUDITD_STEM).gz
DOCKER_AUDITD_DBG = $(DOCKER_AUDITD_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_AUDITD)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BOOKWORM)

$(DOCKER_AUDITD)_PATH = $(DOCKERS_PATH)/$(DOCKER_AUDITD_STEM)

$(DOCKER_AUDITD)_VERSION = 1.0.0
$(DOCKER_AUDITD)_PACKAGE_NAME = auditd

SONIC_DOCKER_IMAGES += $(DOCKER_AUDITD)
SONIC_BOOKWORM_DOCKERS += $(DOCKER_AUDITD)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_AUDITD)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_AUDITD_DBG)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_AUDITD_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_AUDITD_DBG)

$(DOCKER_AUDITD)_CONTAINER_NAME = auditd
$(DOCKER_AUDITD)_RUN_OPT += -t --privileged --pid=host
$(DOCKER_AUDITD)_RUN_OPT += -v /lib/systemd/system:/lib/systemd/system:rw
$(DOCKER_AUDITD)_RUN_OPT += -v /etc/audit:/etc/audit:rw
$(DOCKER_AUDITD)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_AUDITD)_RUN_OPT += -v /etc/localtime:/etc/localtime:ro

