# docker image for teamd agent

DOCKER_TEAMD_STEM = docker-teamd
DOCKER_TEAMD = $(DOCKER_TEAMD_STEM).gz
DOCKER_TEAMD_DBG = $(DOCKER_TEAMD_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_TEAMD)_PATH = $(DOCKERS_PATH)/$(DOCKER_TEAMD_STEM)

$(DOCKER_TEAMD)_DEPENDS += $(LIBTEAMDCTL) $(LIBTEAM_UTILS)
$(DOCKER_TEAMD)_DBG_DEPENDS = $($(DOCKER_SWSS_LAYER_BOOKWORM)_DBG_DEPENDS)
$(DOCKER_TEAMD)_DBG_DEPENDS += $(LIBTEAMDCTL_DBG) $(LIBTEAM_UTILS_DBG)

$(DOCKER_TEAMD)_DBG_IMAGE_PACKAGES = $($(DOCKER_SWSS_LAYER_BOOKWORM)_DBG_IMAGE_PACKAGES)

$(DOCKER_TEAMD)_LOAD_DOCKERS += $(DOCKER_SWSS_LAYER_BOOKWORM)

$(DOCKER_TEAMD)_VERSION = 1.0.0
$(DOCKER_TEAMD)_PACKAGE_NAME = teamd
$(DOCKER_TEAMD)_WARM_SHUTDOWN_BEFORE = syncd
$(DOCKER_TEAMD)_WARM_SHUTDOWN_AFTER = swss
$(DOCKER_TEAMD)_FAST_SHUTDOWN_BEFORE = syncd
$(DOCKER_TEAMD)_FAST_SHUTDOWN_AFTER = swss

SONIC_DOCKER_IMAGES += $(DOCKER_TEAMD)
ifeq ($(INCLUDE_TEAMD), y)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_TEAMD)
endif

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_TEAMD_DBG)
ifeq ($(INCLUDE_TEAMD), y)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_TEAMD_DBG)
endif

$(DOCKER_TEAMD)_CONTAINER_NAME = teamd
$(DOCKER_TEAMD)_RUN_OPT += -t --cap-add=NET_ADMIN
$(DOCKER_TEAMD)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_TEAMD)_RUN_OPT += -v /etc/localtime:/etc/localtime:ro 
$(DOCKER_TEAMD)_RUN_OPT += -v /host/warmboot:/var/warmboot

$(DOCKER_TEAMD)_BASE_IMAGE_FILES += teamdctl:/usr/bin/teamdctl

SONIC_BOOKWORM_DOCKERS += $(DOCKER_TEAMD)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_TEAMD_DBG)
