# docker image for auditd watchdog

DOCKER_AUDITD_WATCHDOG_STEM = docker-auditd-watchdog
DOCKER_AUDITD_WATCHDOG = $(DOCKER_AUDITD_WATCHDOG_STEM).gz
DOCKER_AUDITD_WATCHDOG_DBG = $(DOCKER_AUDITD_WATCHDOG_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_AUDITD_WATCHDOG)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BOOKWORM)

$(DOCKER_AUDITD_WATCHDOG)_PATH = $(DOCKERS_PATH)/$(DOCKER_AUDITD_WATCHDOG_STEM)

$(DOCKER_AUDITD_WATCHDOG)_VERSION = 1.0.0
$(DOCKER_AUDITD_WATCHDOG)_PACKAGE_NAME = auditd_watchdog

SONIC_DOCKER_IMAGES += $(DOCKER_AUDITD_WATCHDOG)
SONIC_BOOKWORM_DOCKERS += $(DOCKER_AUDITD_WATCHDOG)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_AUDITD_WATCHDOG)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_AUDITD_WATCHDOG_DBG)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_AUDITD_WATCHDOG_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_AUDITD_WATCHDOG_DBG)

$(DOCKER_AUDITD_WATCHDOG)_CONTAINER_NAME = auditd_watchdog
$(DOCKER_AUDITD_WATCHDOG)_RUN_OPT += -t --privileged --pid=host
$(DOCKER_AUDITD_WATCHDOG)_RUN_OPT += -v /lib/systemd/system:/lib/systemd/system:rw
$(DOCKER_AUDITD_WATCHDOG)_RUN_OPT += -v /etc/audit:/etc/audit:rw
$(DOCKER_AUDITD_WATCHDOG)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_AUDITD_WATCHDOG)_RUN_OPT += -v /etc/localtime:/etc/localtime:ro

$(DOCKER_AUDITD_WATCHDOG)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)
