# docker image for sysmgr

DOCKER_SYSMGR_STEM = docker-sysmgr
DOCKER_SYSMGR = $(DOCKER_SYSMGR_STEM).gz
DOCKER_SYSMGR_DBG = $(DOCKER_SYSMGR_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_SYSMGR)_PATH = $(DOCKERS_PATH)/$(DOCKER_SYSMGR_STEM)

$(DOCKER_SYSMGR)_DEPENDS += $(SYSMGR)
$(DOCKER_SYSMGR)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_DEPENDS)
$(DOCKER_SYSMGR)_DBG_DEPENDS += $(SYSMGR_DBG) $(LIBSWSSCOMMON_DBG)
$(DOCKER_SYSMGR)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_IMAGE_PACKAGES)

$(DOCKER_SYSMGR)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BOOKWORM)
$(DOCKER_SYSMGR)_LOAD_DOCKERS += $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_LOAD_DOCKERS)

$(DOCKER_SYSMGR)_VERSION = 1.0.0
$(DOCKER_SYSMGR)_PACKAGE_NAME = sysmgr

SONIC_DOCKER_IMAGES += $(DOCKER_SYSMGR)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_SYSMGR)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_SYSMGR_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_SYSMGR_DBG)

$(DOCKER_SYSMGR)_CONTAINER_NAME = sysmgr
$(DOCKER_SYSMGR)_RUN_OPT += -v /var/run/dbus:/var/run/dbus:rw  
$(DOCKER_SYSMGR)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro  
$(DOCKER_SYSMGR)_GIT_REPOSITORIES += "sonic-swss"
$(DOCKER_SYSMGR)_GIT_REPOSITORIES += "sonic-swss-common"

$(DOCKER_SYSMGR)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)

SONIC_BOOKWORM_DOCKERS += $(DOCKER_SYSMGR)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_SYSMGR_DBG)
