# docker image for bmp watchdog

DOCKER_BMP_WATCHDOG_STEM = docker-bmp-watchdog
DOCKER_BMP_WATCHDOG = $(DOCKER_BMP_WATCHDOG_STEM).gz
DOCKER_BMP_WATCHDOG_DBG = $(DOCKER_BMP_WATCHDOG_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_BMP_WATCHDOG)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BOOKWORM)

$(DOCKER_BMP_WATCHDOG)_PATH = $(DOCKERS_PATH)/$(DOCKER_BMP_WATCHDOG_STEM)

$(DOCKER_BMP_WATCHDOG)_VERSION = 1.0.0
$(DOCKER_BMP_WATCHDOG)_PACKAGE_NAME = bmp_watchdog

SONIC_DOCKER_IMAGES += $(DOCKER_BMP_WATCHDOG)
SONIC_BOOKWORM_DOCKERS += $(DOCKER_BMP_WATCHDOG)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_BMP_WATCHDOG)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_BMP_WATCHDOG_DBG)
SONIC_BOOKWORM_DBG_DOCKERS += $(DOCKER_BMP_WATCHDOG_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_BMP_WATCHDOG_DBG)

$(DOCKER_BMP_WATCHDOG)_CONTAINER_NAME = bmp_watchdog
$(DOCKER_BMP_WATCHDOG)_RUN_OPT += -t --privileged --pid=host
$(DOCKER_BMP_WATCHDOG)_RUN_OPT += -v /lib/systemd/system:/lib/systemd/system:rw
$(DOCKER_BMP_WATCHDOG)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_BMP_WATCHDOG)_RUN_OPT += -v /etc/localtime:/etc/localtime:ro

