# libyang3 python3 deb package

LIBYANG3_PY3_VERSION = 3.1.0
LIBYANG3_PY3_SUBVERSION = 1
LIBYANG3_PY3_FULLVERSION = $(LIBYANG3_PY3_VERSION)-$(LIBYANG3_PY3_SUBVERSION)

export LIBYANG3_PY3_VERSION
export LIBYANG3_PY3_SUBVERSION
export LIBYANG3_PY3_FULLVERSION

LIBYANG3_PY3 = python3-libyang_$(LIBYANG3_PY3_FULLVERSION)_$(CONFIGURED_ARCH).deb
$(LIBYANG3_PY3)_SRC_PATH = $(SRC_PATH)/libyang3-py3
$(LIBYANG3_PY3)_DEPENDS += $(LIBYANG3) $(LIBYANG3_DEV)
$(LIBYANG3_PY3)_RDEPENDS += $(LIBYANG3)
SONIC_MAKE_DEBS += $(LIBYANG3_PY3)

export LIBYANG3_PY3

