SONIC_SUPERVISORD_UTILITIES_RS_VERSION = 1.0.0
SONIC_SUPERVISORD_UTILITIES_RS_NAME = sonic-supervisord-utilities-rs

SONIC_SUPERVISORD_UTILITIES_RS = $(SONIC_SUPERVISORD_UTILITIES_RS_NAME)_$(SONIC_SUPERVISORD_UTILITIES_RS_VERSION)_$(CONFIGURED_ARCH).deb
$(SONIC_SUPERVISORD_UTILITIES_RS)_SRC_PATH = $(SRC_PATH)/sonic-supervisord-utilities-rs
$(SONIC_SUPERVISORD_UTILITIES_RS)_VERSION = $(SONIC_SUPERVISORD_UTILITIES_RS_VERSION)
$(SONIC_SUPERVISORD_UTILITIES_RS)_NAME = $(SONIC_SUPERVISORD_UTILITIES_RS_NAME)
$(SONIC_SUPERVISORD_UTILITIES_RS)_DEPENDS = $(LIBSWSSCOMMON_DEV)
$(SONIC_SUPERVISORD_UTILITIES_RS)_RDEPENDS = $(LIBSWSSCOMMON)

SONIC_DPKG_DEBS += $(SONIC_SUPERVISORD_UTILITIES_RS)

SONIC_SUPERVISORD_UTILITIES_RS_DBG = $(SONIC_SUPERVISORD_UTILITIES_RS_NAME)-dbgsym_$(SONIC_SUPERVISORD_UTILITIES_RS_VERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(SONIC_SUPERVISORD_UTILITIES_RS),$(SONIC_SUPERVISORD_UTILITIES_RS_DBG)))