# sonic_supervisord_utilities Python wheel

SONIC_SUPERVISORD_UTILITIES = sonic_supervisord_utilities-1.0-py3-none-any.whl
$(SONIC_SUPERVISORD_UTILITIES)_SRC_PATH = $(SRC_PATH)/sonic-supervisord-utilities
$(SONIC_SUPERVISORD_UTILITIES)_PYTHON_VERSION = 3
$(SONIC_SUPERVISORD_UTILITIES)_DEPENDS = $(SONIC_PY_COMMON_PY3)
$(SONIC_SUPERVISORD_UTILITIES)_DEBS_DEPENDS = $(LIBSWSSCOMMON) $(PYTHON3_SWSSCOMMON)
SONIC_PYTHON_WHEELS += $(SONIC_SUPERVISORD_UTILITIES)

export sonic_supervisord_utilities_py3_wheel_path="$(addprefix $(PYTHON_WHEELS_PATH)/,$(SONIC_SUPERVISORD_UTILITIES))"
