SONIC_CTRMGRD_RS_VERSION = 1.0.0
SONIC_CTRMGRD_RS_NAME = sonic-ctrmgrd-rs

SONIC_CTRMGRD_RS = $(SONIC_CTRMGRD_RS_NAME)_$(SONIC_CTRMGRD_RS_VERSION)_$(CONFIGURED_ARCH).deb
$(SONIC_CTRMGRD_RS)_SRC_PATH = $(SRC_PATH)/sonic-ctrmgrd-rs
$(SONIC_CTRMGRD_RS)_VERSION = $(SONIC_CTRMGRD_RS_VERSION)
$(SONIC_CTRMGRD_RS)_NAME = $(SONIC_CTRMGRD_RS_NAME)
$(SONIC_CTRMGRD_RS)_DEPENDS = $(LIBSWSSCOMMON_DEV)
$(SONIC_CTRMGRD_RS)_RDEPENDS = $(LIBSWSSCOMMON)

SONIC_DPKG_DEBS += $(SONIC_CTRMGRD_RS)

SONIC_CTRMGRD_RS_DBG = $(SONIC_CTRMGRD_RS_NAME)-dbgsym_$(SONIC_CTRMGRD_RS_VERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(SONIC_CTRMGRD_RS),$(SONIC_CTRMGRD_RS_DBG)))
