SONIC_NETTOOLS_VERSION = 0.0.1-0

export SONIC_NETTOOLS_VERSION

SONIC_NETTOOLS = sonic-nettools_$(SONIC_NETTOOLS_VERSION)_$(CONFIGURED_ARCH).deb
$(SONIC_NETTOOLS)_SRC_PATH = $(SRC_PATH)/sonic-nettools
SONIC_DPKG_DEBS += $(SONIC_NETTOOLS)

SONIC_NETTOOLS_DBG = sonic-nettools-dbgsym_0.0.1-0_$(CONFIGURED_ARCH).deb
$(SONIC_NETTOOLS_DBG)_DEPENDS += $(SONIC_NETTOOLS)
$(SONIC_NETTOOLS_DBG)_RDEPENDS += $(SONIC_NETTOOLS)
$(eval $(call add_derived_package,$(SONIC_NETTOOLS),$(SONIC_NETTOOLS_DBG)))
