SONIC_NETTOOLS_VERSION = 0.0.1-0

export SONIC_NETTOOLS_VERSION

SONIC_NETTOOLS = sonic-nettools_$(SONIC_NETTOOLS_VERSION)_$(CONFIGURED_ARCH).deb
$(SONIC_NETTOOLS)_SRC_PATH = $(SRC_PATH)/sonic-nettools
SONIC_DPKG_DEBS += $(SONIC_NETTOOLS)
