# sonic-bmp package
SONIC_BMPD = sonic-bmp_0.1_$(CONFIGURED_ARCH).deb
$(SONIC_BMPD)_SRC_PATH = $(SRC_PATH)/sonic-bmp
$(SONIC_BMPD)_DEPENDS  =  $(LIBSWSSCOMMON_DEV) $(LIBSWSSCOMMON)
$(SONIC_BMPD)_RDEPENDS = $(LIBSWSSCOMMON)
SONIC_DPKG_DEBS += $(SONIC_BMPD)

SONIC_BMPD_DBG = sonic-bmp-dbgsym_0.1_$(CONFIGURED_ARCH).deb
$(SONIC_BMPD_DBG)_DEPENDS += $(SONIC_BMPD)
$(SONIC_BMPD_DBG)_RDEPENDS += $(SONIC_BMPD)
$(eval $(call add_derived_package,$(SONIC_BMPD),$(SONIC_BMPD_DBG)))
