SONIC_HOST_SERVICES_RS_VERSION = 1.0.0
SONIC_HOST_SERVICES_RS_NAME = sonic-host-services-rs

SONIC_HOST_SERVICES_RS = $(SONIC_HOST_SERVICES_RS_NAME)_$(SONIC_HOST_SERVICES_RS_VERSION)_$(CONFIGURED_ARCH).deb
$(SONIC_HOST_SERVICES_RS)_SRC_PATH = $(SRC_PATH)/sonic-host-services
$(SONIC_HOST_SERVICES_RS)_VERSION = $(SONIC_HOST_SERVICES_RS_VERSION)
$(SONIC_HOST_SERVICES_RS)_NAME = $(SONIC_HOST_SERVICES_RS_NAME)
$(SONIC_HOST_SERVICES_RS)_DEPENDS = $(LIBSWSSCOMMON_DEV)
$(SONIC_HOST_SERVICES_RS)_RDEPENDS = $(LIBSWSSCOMMON)

SONIC_DPKG_DEBS += $(SONIC_HOST_SERVICES_RS)

SONIC_HOST_SERVICES_RS_DBG = $(SONIC_HOST_SERVICES_RS_NAME)-dbgsym_$(SONIC_HOST_SERVICES_RS_VERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(SONIC_HOST_SERVICES_RS),$(SONIC_HOST_SERVICES_RS_DBG)))
