SYSLOG_COUNTER_VERSION = 1.0.0
export SYSLOG_COUNTER_VERSION

SYSLOG_COUNTER = syslog-counter_$(SYSLOG_COUNTER_VERSION)_$(CONFIGURED_ARCH).deb
$(SYSLOG_COUNTER)_DEPENDS += $(LIBSWSSCOMMON_DEV)
$(SYSLOG_COUNTER)_RDEPENDS +=  $(LIBSWSSCOMMON)
$(SYSLOG_COUNTER)_SRC_PATH = $(SRC_PATH)/syslog-counter
SONIC_DPKG_DEBS += $(SYSLOG_COUNTER)
