# SONiC telemetry package

SONIC_TELEMETRY = sonic-gnmi_0.1_$(CONFIGURED_ARCH).deb
$(SONIC_TELEMETRY)_SRC_PATH = $(SRC_PATH)/sonic-gnmi
$(SONIC_TELEMETRY)_DEPENDS  = $(SONIC_MGMT_COMMON) $(SONIC_MGMT_COMMON_CODEGEN) \
    $(LIBSWSSCOMMON_DEV) $(LIBSWSSCOMMON) 
$(SONIC_TELEMETRY)_RDEPENDS = $(LIBSWSSCOMMON)
SONIC_DPKG_DEBS += $(SONIC_TELEMETRY)

SONIC_TELEMETRY_DBG = sonic-gnmi-dbgsym_0.1_$(CONFIGURED_ARCH).deb
$(SONIC_TELEMETRY_DBG)_DEPENDS += $(SONIC_TELEMETRY)
$(SONIC_TELEMETRY_DBG)_RDEPENDS += $(SONIC_TELEMETRY)
$(eval $(call add_derived_package,$(SONIC_TELEMETRY),$(SONIC_TELEMETRY_DBG)))
