# docker image for vs gbsyncd

DOCKER_DASH_ENGINE = docker-dash-engine.gz
$(DOCKER_DASH_ENGINE)_VERSION = 1.0.0
$(DOCKER_DASH_ENGINE)_PACKAGE_NAME = dash-engine
$(DOCKER_DASH_ENGINE)_PATH = $(PLATFORM_PATH)/docker-dash-engine

SONIC_DOCKER_IMAGES += $(DOCKER_DASH_ENGINE)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_DASH_ENGINE)

$(DOCKER_DASH_ENGINE)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BOOKWORM)

$(DOCKER_DASH_ENGINE)_CONTAINER_NAME = dash_engine
$(DOCKER_DASH_ENGINE)_CONTAINER_PRIVILEGED = true
$(DOCKER_DASH_ENGINE)_RUN_OPT += --privileged -t

SONIC_BOOKWORM_DOCKERS += $(DOCKER_DASH_ENGINE)
