# docker image for docker-ptf

DOCKER_PTF = docker-ptf.gz
$(DOCKER_PTF)_PYTHON_WHEELS += $(PTF_PY3)
$(DOCKER_PTF)_PATH = $(DOCKERS_PATH)/docker-ptf
ifeq ($(SONIC_PTF_ENV_PY_VER), mixed)
$(DOCKER_PTF)_DEPENDS += $(LIBTHRIFT) $(PYTHON_THRIFT) $(PTF) $(PYTHON_SAITHRIFT)
else
$(DOCKER_PTF)_DEPENDS += $(PYTHON_SAITHRIFT) $(P4LANG_PI) $(P4LANG_BMV2) $(P4LANG_P4C)
endif
SONIC_DOCKER_IMAGES += $(DOCKER_PTF)
SONIC_BOOKWORM_DOCKERS += $(DOCKER_PTF)
