ARG BASE=p4lang/behavioral-model@sha256:ce45720e28a96a50f275c1b511cd84c2558b62f2cf7a7e506765183bc3fb2e32
## ARG BASE=docker-config-engine-bullseye-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

FROM $BASE AS base

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get install -f -y net-tools supervisor rsyslog  python3-pip
RUN pip3 install supervisord-dependent-startup

COPY ["start.sh", "/usr/bin/"]

## COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
## COPY ["files/supervisor-proc-exit-listener", "/usr/bin"]
## COPY ["critical_processes", "/etc/supervisor/"]

FROM $BASE

## RUN --mount=type=bind,from=base,target=/changes-to-image rsync -axAX --no-D --exclude=/sys --exclude=resolv.conf /changes-to-image/ /
COPY --from=base / /

## ENTRYPOINT ["/usr/bin/supervisord"]
ENTRYPOINT ["/usr/bin/start.sh"]
